# Generated by Django 5.1.6 on 2025-03-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0003_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
